### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nhunzaker**
I had to make this change in order to get the runtime to inject properly. Did I miss something?

### CODE REVIEW

**Comment by sebmck** [comment]
Ping @Couto

**Comment by Couto** [comment]
I did a quick test with a current project and your configuration always results in errors.
Just to make sure, did you enable the runtime option?

**Comment by nhunzaker** [comment]
I believe so. This is how I have the loader configured at any rate:

```javascript
{
  test    : /\.jsx*$/,
  exclude : /node_modules/,
  loader  : 'envify-loader!6to5-loader?experimental=true&modules=common'
},
```

**Comment by nhunzaker** [comment]
Aye, and here's the error I'm getting:

```
Module not found: Error: Cannot resolve module 'imports' in {file}
```

To produce this error, I have the loader configured like so:

```javascript

module.exports = {
  plugins: [
    new WebPack.ProvidePlugin({
      to5Runtime: "imports?global=>{}!exports-loader?global.to5Runtime!6to5/runtime"
    })
  ],
  module: {
    loaders: [
      {
        test    : /\.jsx*$/,
        exclude : /node_modules/,
        loader  : 'envify-loader!6to5-loader?experimental=true&modules=common&runtime=true'
      }
    ]
  }
}

**Comment by Couto** [comment]
You need to install the loaders: `npm install imports-loader exports-loader --save-dev` since they aren't included by default with webpack.

**Comment by nhunzaker** [comment]
Ahhhh, of course. Thoughts on including this in the readme?

**Comment by Couto** [comment]
I will.
Could you confirm me that this doesn't work?

```
module.exports = {
  plugins: [
    new WebPack.ProvidePlugin({
      to5Runtime: "6to5/runtime"
    })
  ],
  module: {
    loaders: [
      {
        test    : /\.jsx*$/,
        exclude : /node_modules/,
        loader  : '6to5-loader?experimental&runtime&modules=common'
      }
    ]
  }
}
```
Because it would really be nice that the example above could in fact work, but I think it doesn't

**Comment by nhunzaker** [comment]
It _does_ work!

**Comment by nhunzaker** [comment]
Well.. actually. It just successfully compiles. It looks like the run time is not present. Sorry for jumping the gun

**Comment by nhunzaker** [comment]
@Couto curiously, if I remove the `runtime` flag, your example does work. Any idea why this is the case?

**Comment by Dashed** [comment]
@Couto Probably need to clarify that `imports-loader exports-loader` are needed as deps, especially for folks not aware of webpack loaders.

**Comment by nhunzaker** [comment]
Yeah, I think that's the key issue. I think even a quick "install imports-loader and exports-loader" would be sufficient

**Comment by Couto** [comment]
I've just added the instructions to install the loaders. Since English is not my first language I would appreciate some revision.

**Comment by nhunzaker** [comment]
Looks good to me!

**Pull request closed without merging**
